/* soapClient.cpp
   Generated by gSOAP 2.8.8 from server.h

Copyright(C) 2000-2012, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapClient.cpp ver 2.8.8 2016-06-24 11:22:59 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__GetCity(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *Secret, std::string *result)
{	struct ns__GetCity soap_tmp_ns__GetCity;
	struct ns__GetCityResponse *soap_tmp_ns__GetCityResponse;
	soap->encodingStyle = NULL;
	soap_tmp_ns__GetCity.Secret = Secret;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns__GetCity(soap, &soap_tmp_ns__GetCity);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__GetCity(soap, &soap_tmp_ns__GetCity, "ns:GetCity", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__GetCity(soap, &soap_tmp_ns__GetCity, "ns:GetCity", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!result)
		return soap_closesock(soap);
	soap_default_std__string(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_ns__GetCityResponse = soap_get_ns__GetCityResponse(soap, NULL, "ns:GetCityResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (result && soap_tmp_ns__GetCityResponse->result)
		*result = *soap_tmp_ns__GetCityResponse->result;
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.cpp */
